### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by eunju6460** [MohammadMDSA/Darius#5]
<img width="1280" alt="err1" src="https://github.com/MohammadMDSA/Darius/assets/52093930/2619d983-bf04-4e8f-8260-9de76da71804">

<img width="1280" alt="err2" src="https://github.com/MohammadMDSA/Darius/assets/52093930/6e96cbc2-32cf-410a-8582-789611dc4bec">

<img width="1280" alt="err3" src="https://github.com/MohammadMDSA/Darius/assets/52093930/026b3924-bca8-430d-8ba6-338dc75122ce">

<img width="1280" alt="err4" src="https://github.com/MohammadMDSA/Darius/assets/52093930/37049bbb-6560-4453-985b-7264b949fd20">

<img width="1280" alt="err5" src="https://github.com/MohammadMDSA/Darius/assets/52093930/58f2be2d-57cc-436d-9b7e-6b9c7414ea76">

<img width="1279" alt="err6" src="https://github.com/MohammadMDSA/Darius/assets/52093930/c4d9e926-9312-4f20-b366-e15b64daf4eb">

**Comment by MohammadMDSA** [comment]
Hi!
You have generated a VS project. I recommend building with Cmake directly, which is supported by VS too. You simply have to open the project directory with VS. I have never tested it with VS generated projects.

There is a step before building which is code generation being handled by cmake (not sure if VS is doing it right). All the files you are missing (*.generated.hpp, *.sgenerated.hpp) are the productions of that step. If you had any questions regarding CMake build or else, I'll be glad to help.
