### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by eunju6460** [MohammadMDSA/Darius#6]
C:\Users\alla>git clone --recursive https://github.com/MohammadMDSA/Darius.git
Cloning into 'Darius'...
remote: Enumerating objects: 20507, done.
remote: Counting objects: 100% (7052/7052), done.
remote: Compressing objects: 100% (2390/2390), done.
remote: Total 20507 (delta 4718), reused 6892 (delta 4603), pack-reused 13455 (from 1)
Receiving objects: 100% (20507/20507), 209.18 MiB | 4.91 MiB/s, done.
Resolving deltas: 100% (14233/14233), done.
Updating files: 100% (2164/2164), done.
Filtering content: 100% (20/20), 528.49 MiB | 8.62 MiB/s, done.
Submodule 'DariusHeaderTool' (https://github.com/MohammadMDSA/DariusHeaderTool) registered for path 'DariusHeaderTool'
Submodule 'Demo/Assets/PolygonMilitary' (https://github.com/MohammadMDSA/Darius-Polygon-Military.git) registered for path 'Demo/Assets/PolygonMilitary'
Submodule 'src/Libs/DirectXTK12' (https://github.com/microsoft/DirectXTK12.git) registered for path 'src/Libs/DirectXTK12'
Submodule 'src/Libs/DirectXTex' (https://github.com/microsoft/DirectXTex) registered for path 'src/Libs/DirectXTex'
Submodule 'src/Libs/StringId' (https://github.com/foonathan/string_id.git) registered for path 'src/Libs/StringId'
Submodule 'src/Libs/enkiTS' (https://github.com/dougbinks/enkiTS) registered for path 'src/Libs/enkiTS'
Submodule 'src/Libs/fjs' (https://github.com/MohammadMDSA/fiber-job-system) registered for path 'src/Libs/fjs'
Submodule 'src/Libs/imgui_wrapper/ImGuiFileDialog' (https://github.com/aiekick/ImGuiFileDialog.git) registered for path 'src/Libs/imgui_wrapper/ImGuiFileDialog'
Submodule 'src/Libs/imgui_wrapper/implot' (https://github.com/epezent/implot.git) registered for path 'src/Libs/imgui_wrapper/implot'
Cloning into 'C:/Users/alla/Darius/DariusHeaderTool'...
remote: Enumerating objects: 6994, done.
remote: Counting objects: 100% (401/401), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 6994 (delta 277), reused 358 (delta 251), pack-reused 6593 (from 1)
Receiving objects: 100% (6994/6994), 415.18 MiB | 5.58 MiB/s, done.
Resolving deltas: 100% (4957/4957), done.
Cloning into 'C:/Users/alla/Darius/Demo/Assets/PolygonMilitary'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/MohammadMDSA/Darius-Polygon-Military.git/' not found
fatal: clone of 'https://github.com/MohammadMDSA/Darius-Polygon-Military.git' into submodule path 'C:/Users/alla/Darius/Demo/Assets/PolygonMilitary' failed
Failed to clone 'Demo/Assets/PolygonMilitary'. Retry scheduled
Cloning into 'C:/Users/alla/Darius/src/Libs/DirectXTK12'...
remote: Enumerating objects: 9413, done.
remote: Counting objects: 100% (2665/2665), done.
remote: Compressing objects: 100% (663/663), done.
remote: Total 9413 (delta 2297), reused 2249 (delta 1999), pack-reused 6748 (from 1)
Receiving objects: 100% (9413/9413), 7.19 MiB | 3.92 MiB/s, done.
Resolving deltas: 100% (8155/8155), done.
Cloning into 'C:/Users/alla/Darius/src/Libs/DirectXTex'...
remote: Enumerating objects: 7744, done.
remote: Counting objects: 100% (952/952), done.
remote: Compressing objects: 100% (450/450), done.
remote: Total 7744 (delta 709), reused 683 (delta 498), pack-reused 6792 (from 1)
Receiving objects: 100% (7744/7744), 5.70 MiB | 3.51 MiB/s, done.
Resolving deltas: 100% (6056/6056), done.
Cloning into 'C:/Users/alla/Darius/src/Libs/StringId'...
remote: Enumerating objects: 294, done.
remote: Total 294 (delta 0), reused 0 (delta 0), pack-reused 294 (from 1)
Receiving objects: 100% (294/294), 58.90 KiB | 14.73 MiB/s, done.
Resolving deltas: 100% (198/198), done.
Cloning into 'C:/Users/alla/Darius/src/Libs/enkiTS'...
remote: Enumerating objects: 3381, done.
remote: Counting objects: 100% (612/612), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 3381 (delta 508), reused 557 (delta 471), pack-reused 2769 (from 1)
Receiving objects: 100% (3381/3381), 682.40 KiB | 5.37 MiB/s, done.
Resolving deltas: 100% (2407/2407), done.
Cloning into 'C:/Users/alla/Darius/src/Libs/fjs'...
remote: Enumerating objects: 383, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 383 (delta 1), reused 5 (delta 1), pack-reused 375 (from 1)
Receiving objects: 100% (383/383), 63.60 KiB | 12.72 MiB/s, done.
Resolving deltas: 100% (205/205), done.
Cloning into 'C:/Users/alla/Darius/src/Libs/imgui_wrapper/ImGuiFileDialog'...
remote: Enumerating objects: 3974, done.
remote: Counting objects: 100% (2220/2220), done.
remote: Compressing objects: 100% (1005/1005), done.
remote: Total 3974 (delta 1274), reused 1884 (delta 1197), pack-reused 1754 (from 1)
Receiving objects: 100% (3974/3974), 13.64 MiB | 5.76 MiB/s, done.
Resolving deltas: 100% (2262/2262), done.
Cloning into 'C:/Users/alla/Darius/src/Libs/imgui_wrapper/implot'...
remote: Enumerating objects: 2574, done.
remote: Counting objects: 100% (783/783), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 2574 (delta 730), reused 712 (delta 708), pack-reused 1791 (from 1)
Receiving objects: 100% (2574/2574), 1.58 MiB | 5.39 MiB/s, done.
Resolving deltas: 100% (1672/1672), done.
Cloning into 'C:/Users/alla/Darius/Demo/Assets/PolygonMilitary'...
info: please complete authentication in your browser...
remote: Repository not found.
fatal: repository 'https://github.com/MohammadMDSA/Darius-Polygon-Military.git/' not found
fatal: clone of 'https://github.com/MohammadMDSA/Darius-Polygon-Military.git' into submodule path 'C:/Users/alla/Darius/Demo/Assets/PolygonMilitary' failed
Failed to clone 'Demo/Assets/PolygonMilitary' a second time, aborting

**Comment by MohammadMDSA** [comment]
Hi,
The submodule is another repo of mine which contains premium content of an Unrean Marketplace package, so I made it private. Just clone the repo and exclude Darius Polygon Military.

**Comment by eunju6460** [comment]
How can I exclude it?

I used 
git clone https://github.com/MohammadMDSA/Darius.git
git submodule update --init --recursive 

but same error

**Comment by MohammadMDSA** [comment]
Based on the log you sent, I believe you have already cloned the whole repo recursively except the private one.

**Comment by eunju6460** [comment]
how to exclude submodule PolygonMilitary only?

**Comment by MohammadMDSA** [comment]
[This thread](https://stackoverflow.com/questions/56745097/exclude-submodule-of-a-submodule) should help; however, as I mentioned, you already might have cloned all the submodules excluding the private one since the only error you got cloning it the first time was the private submodule.
